### ISSUE TITLE
Finish populating committee page

### ISSUE THREAD

**Issue by anthony-zhou** [anthony-zhou/cso2021#2]
The committees data is drawn from `data/committees.json`. 

1. Update the committees.json file to include all data on all 9 committees (name, description, FB link, etc.).
2. Update the `src/committees.js` file so it includes other data, like committee heads and a link to the committee FB group.

**Comment by Jeongwoo55** [comment]
I can try to do this one.

**Comment by Jeongwoo55** [comment]
How should I add committee head info? I can add it to the json but I'm not sure how I should format it on the page

**Comment by anthony-zhou** [comment]
Maybe just list their names as a subheading below the committee title?

Another option would be to just give each committee one entire row, with one column for the name, committee heads, and links, one column for the description, and one column for images.

Depends how much information we want to show about each committee, but I think we can err on the side of including more information rather than less.
